apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    run: load-balancer-example
  ports:
    - port: 8008
      # targetPort: 8008
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: hello-world
          image: oblivion208/flask-demo-container
          ports:
            - containerPort: 8008
              protocol: TCP
